travis:
  secure:
    BINSTAR_TOKEN: BmGcRbYZfgYlZOnkj1Pn9tFIOjUk5Eh4T8vPfSmFq+DQFUi4fiOsCB3X3ihynkSuX78koEacARCVdmBc/k6ptA8L/36Qp/e6cD1aTImcEIvx8HllW+WraZXWGF0nhn6KVuQ3YEGfw35Ni62hpDlbXXsGIoAJz8hI9QNefunOYVJt8suebIM67OGoMiC/RRp9dz9azdmc40v9axFmou+XZCdYSO5USncg2hhXQhTAqiNxXO1CL32syngm1dX5BvNKEmKah2C/x/fuv2WiTl4FWkygZJNKNn+LmeRq2B3SALUzWy3ZyRPYv7nkFN29JEBiUhROsz/SqeO2iE7so8+SmPNkh9DRMsqZPLuTlZI8RUqob4zwBC4gvX4yrU50D9g7WCnAMLZS4LoeaNq9q3mwZl9BXFdpKi+dYAtFMqZr4Px62Tjn8Vb+1ZqUWid9zWWUvHCRH0KDOGWKFQVnzs+gfWMKeQB3CoqwRNvyCxdr4vbCxed1FTb/OtYpKgdIaaNQ6NSzVH28/nxH+OoUoWRULZ69oRfogHloQCnm6TR9O6yVyHkFuqsRpHy1xTzH/n0KPVTSklhbIjfSNgGvoV16T3iWwAY9itwY+kIsx91B1XOMRNDNa3xkvpw421cSVHZ2NkGTWdWoaQqDR64gtluEZIqsGsAbQGns92GeBlM7ad0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
